# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.9"                                                                                                                                                                                              

os: linux
dist: xenial

jobs:
  include:
    - stage: Testes

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;

    - # Segundo Job do Stage de Teste
      name: "Testes de Qualidade e Seguranca"

      install:
        - pip install coverage
        - pip install flask flask-wtf coverage

      script:
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;

      addons:
        sonarcloud:
          organization: gabrielpiazzalunga
          token: ${SONAR_TOKEN}

    - stage: Deploy STG
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api 
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-gabriel-stg
        on: 
          branch: main

    - stage: Teste em STG
      name: "Get na API do stage"
      script: "curl https://devopslab-gabriel-stg.herokuapp.com/"

    - stage: Deploy PROD
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-gabriel
        on:
          branch: main
# Ao final do arquivo deverá ter as linhas abaixo                                                                                                                                                    
notifications:
 slack:
  secure: RbrczzvgM8FFsjCMwDeWcWYiTpH3VhoIyLJVmW91Tj5zSNPY55AA/4K98wsqULHsK1KJCbRiOymOSB4Zj/TSDFP8IsqvaKT+tGkMQ4LcvPdGbZBCb/L16Bs04fvyia03rebGBWydazwa0tukMlzPouM5BRIWW62bo1Le4EK4NhwkfbTuhM4D5IcLnfOPGmiQVPL52q3OHOpTA9nzYVAPkfSmJyIQhCukNkE7NUbzxyEDMQ47iYAKJUzXEOSF9ynz2QVJC8yrbxypk1mV6RrOZV2oD4xIIk+gnGglLS1gbAUEVxCLBw0VWeYQrHsj1Xr7SBihgdDnkZAPGoFIZFambeCBB7ryaUTfApB9thfdy3y0amkaJLJmK0Zk9d5YhHTh4ClzMhrPcuvOTs897p13r4NwAP0ohubYU39DbStMhs83Zut7mXxIxA6Cs/90q2Cxv6PSykuSkKAKa0vklLU/gsgWgBQ7I4aTOd4YXOVDfkXVK5dz2yYcwoGrUoNE/nCTalUynRM7zsrRc8nmxQAtuJDS4+5vJqAVYAYUBsRS16eH0PMWw96AF7s3vcMtSnaN7fmJtXUHc9dv+qiRQxHnEW6rVwHBoLEM+JDvNtpFg7KpXk6aCHzZOp0jHqFcn6mPHeNZNjIznRpOf1QZH5f13DCVhii8LPsdBB4G/b0fkhQ=
